-- ============================================================================
-- Way Suplementos — Schema: Controle de Estoque (Lote/Validade + Remanejamento)
-- Execute este script no SQL Editor do Supabase.
--
-- Estas tabelas (produtos/lojas/lotes/movimentacoes/perdas) são as usadas hoje
-- pelo sistema em django_app/ (models com managed=False, ver estoque/models.py
-- lá dentro). Este módulo substituiu um schema ainda mais antigo (produtos com
-- validade inline, filiais, envios_lojas) — essas tabelas antigas não são
-- apagadas por este script e podem ainda existir órfãs no banco.
-- ============================================================================

-- 1. Catálogo de produtos (sem validade/lote — isso agora vive em "lotes")
CREATE TABLE IF NOT EXISTS produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras TEXT UNIQUE NOT NULL,
    nome TEXT NOT NULL,
    marca TEXT
);

-- 2. Lojas (inclui o próprio CD como uma "loja")
CREATE TABLE IF NOT EXISTS lojas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT UNIQUE NOT NULL
);

-- 3. Lotes: saldo de um produto, com validade, numa loja específica.
-- IMPORTANTE: o app nunca deleta uma linha de "lotes" (só zera a quantidade),
-- para que "movimentacoes" e "perdas" continuem rastreáveis até um lote consumido.
--
-- Fluxo de aprovação: uma entrada lançada pelo perfil 'cd' nasce com
-- status='aguardando_aprovacao' e só conta como estoque disponível (aparece na
-- Planilha Compartilhada) depois que 'compra_venda' ou 'admin' aprova (status
-- vira 'aprovado'). Entradas lançadas por 'compra_venda'/'admin' já nascem
-- aprovadas. Remanejamento e baixa por perda só operam sobre lotes aprovados.
CREATE TABLE IF NOT EXISTS lotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL REFERENCES produtos(id),
    lote TEXT,
    validade DATE NOT NULL,
    loja_atual_id BIGINT NOT NULL REFERENCES lojas(id),
    quantidade INT NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    status TEXT NOT NULL DEFAULT 'aprovado' CHECK (status IN ('aguardando_aprovacao', 'aprovado', 'rejeitado')),
    criado_por TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    aprovado_por TEXT,
    aprovado_em TIMESTAMP WITH TIME ZONE,
    motivo_rejeicao TEXT
);
-- Se a tabela "lotes" já existia (criada antes deste fluxo de aprovação), as
-- linhas abaixo adicionam as colunas que faltam sem apagar nada (idempotente,
-- seguro rodar de novo). Isso tem que vir ANTES dos CREATE INDEX abaixo, porque
-- se a tabela já existia, o CREATE TABLE IF NOT EXISTS acima foi ignorado (não
-- altera tabela existente) — então a coluna "status" só passa a existir aqui.
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'aprovado' CHECK (status IN ('aguardando_aprovacao', 'aprovado', 'rejeitado'));
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS criado_por TEXT;
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS aprovado_por TEXT;
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS aprovado_em TIMESTAMP WITH TIME ZONE;
ALTER TABLE lotes ADD COLUMN IF NOT EXISTS motivo_rejeicao TEXT;

CREATE INDEX IF NOT EXISTS idx_lotes_busca ON lotes (produto_id, validade, loja_atual_id, lote);
CREATE INDEX IF NOT EXISTS idx_lotes_loja ON lotes (loja_atual_id);
CREATE INDEX IF NOT EXISTS idx_lotes_status ON lotes (status);

-- 4. Movimentações: histórico de entradas e remanejamentos
CREATE TABLE IF NOT EXISTS movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_id BIGINT NOT NULL REFERENCES lotes(id),
    tipo TEXT NOT NULL CHECK (tipo IN ('entrada', 'remanejamento')),
    loja_origem_id BIGINT REFERENCES lojas(id),   -- nulo quando tipo = 'entrada'
    loja_destino_id BIGINT NOT NULL REFERENCES lojas(id),
    quantidade INT NOT NULL,
    data TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    responsavel TEXT,
    observacoes TEXT  -- extra além do briefing original, para guardar NF/guia de transferência
);
CREATE INDEX IF NOT EXISTS idx_movimentacoes_data ON movimentacoes (data DESC);

-- 5. Perdas (mantida como já existia no app antigo — só migrando a referência de
-- filial_id (tabela "filiais", removida) para loja_id (tabela "lojas" nova), e
-- adicionando lote_id para rastreabilidade).
--
-- Se a tabela "perdas" já existir no schema antigo (com coluna filial_id), rode a
-- migração manual comentada logo abaixo em vez do CREATE TABLE.
CREATE TABLE IF NOT EXISTS perdas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    loja_id BIGINT REFERENCES lojas(id),
    lote_id BIGINT REFERENCES lotes(id),
    codigo_barras TEXT,
    nome TEXT,
    marca TEXT,
    validade TEXT,
    quantidade INT,
    custo_unitario NUMERIC(10, 2) DEFAULT 0.00,
    prejuizo_total NUMERIC(10, 2) DEFAULT 0.00,
    motivo TEXT DEFAULT 'Vencimento',
    observacoes TEXT,
    usuario TEXT
);

-- Migração manual (rode SÓ SE a tabela "perdas" antiga já existir com "filial_id"):
-- ALTER TABLE perdas RENAME COLUMN filial_id TO loja_id;
-- ALTER TABLE perdas ADD COLUMN IF NOT EXISTS lote_id BIGINT REFERENCES lotes(id);
-- (a FK de loja_id continuará apontando para "filiais" até você recriar a
--  constraint manualmente apontando para "lojas", depois de migrar os dados de
--  "filiais" para "lojas".)

-- 6. Usuários (ÓRFÃ / SEM USO ATUAL): perfil e liberação de acesso de cada
-- conta de login via Supabase Auth. Era usada pela versão anterior em
-- Streamlit, já removida do repositório. O sistema atual (django_app/) usa as
-- tabelas próprias do Django (auth_user, auth_group) para perfil/login, não
-- esta tabela. Mantida aqui só como registro histórico; a linha continua a
-- existir no banco (dados não foram apagados), mas nada mais escreve nela.
--
-- Perfis daquela versão: 'cd' (só lança recebimento, fica pendente),
-- 'compra_venda' (acesso total + aprova/rejeita), 'admin' (acesso total +
-- gestão de usuários) — mesmo desenho de perfis foi recriado no Django como
-- Grupos "CD" / "Compra e Venda" / "Coordenador/Admin".
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    apelido TEXT UNIQUE NOT NULL,
    perfil TEXT CHECK (perfil IN ('cd', 'compra_venda', 'admin')),
    ativo BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Projetos Supabase recentes vêm com Row Level Security habilitado por padrão em
-- tabelas novas do schema public. Este app não usa RLS em nenhuma tabela (o
-- controle de acesso é feito no Python — ver nota abaixo) — sem esta linha, o
-- próprio login falha ao tentar criar a linha do usuário na primeira vez
-- (erro 42501 "new row violates row-level security policy for table usuarios").
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

-- Nota de segurança: assim como o restante deste app, o controle de acesso é
-- feito no código Python (Streamlit roda no servidor, nunca no navegador do
-- usuário), não por Row Level Security no Postgres. Isso é consistente com
-- como as outras tabelas já funcionam aqui, mas significa que qualquer coisa
-- com a mesma chave do Supabase usada no app.py (SUPABASE_KEY) tem acesso
-- irrestrito a todas as tabelas, inclusive esta. Se um dia esse app ganhar
-- outro cliente (ex: chamadas diretas do navegador), vale revisitar isso e
-- habilitar RLS de verdade.
