# Generated by Django 6.1 on 2026-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'lojas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Lote')),
                ('validade', models.DateField()),
                ('quantidade', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aguardando_aprovacao', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=30)),
                ('criado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lotes',
                'ordering': ['validade'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('remanejamento', 'Remanejamento')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('responsavel', models.CharField(blank=True, max_length=150, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando_aprovacao', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=30)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-data'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=64, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
    ]
