# Generated by Django 6.1 on 2026-08-27 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_criar_grupos_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('data_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_decididas', to=settings.AUTH_USER_MODEL)),
                ('loja_destino', models.ForeignKey(db_column='loja_destino_id', on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='estoque.loja')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notas_fiscais',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('lote_gerado', models.ForeignKey(blank=True, db_column='lote_gerado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_nota_fiscal_origem', to='estoque.lote')),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota_fiscal', to='estoque.produto')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.notafiscal')),
            ],
            options={
                'db_table': 'itens_nota_fiscal',
                'ordering': ['id'],
            },
        ),
    ]
