# Generated by Django 6.1 on 2026-08-27 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_notafiscal_itemnotafiscal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('em_rota', 'Em Rota'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada')], default='em_rota', max_length=20)),
                ('loja_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_saida', to='estoque.loja')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_atribuidas', to=settings.AUTH_USER_MODEL)),
                ('responsavel_envio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notas_fiscais_saida',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando'), ('recebido', 'Recebido'), ('atrasado', 'Atrasado')], default='aguardando', max_length=20)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('loja_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_recebidas', to='estoque.loja')),
                ('nota_fiscal_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='estoque.notafiscalsaida')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_recebidas_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paradas_rota',
                'ordering': ['nota_fiscal_saida', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(db_column='produto_id', on_delete=django.db.models.deletion.PROTECT, related_name='itens_parada', to='estoque.produto')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.paradarota')),
            ],
            options={
                'db_table': 'itens_parada',
                'ordering': ['id'],
            },
        ),
    ]
